on:
  schedule:
    - cron: '30 12 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: install-docker-compose-v2/scripts/update-version-file.sh

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .

          changes=$(git status --porcelain)

          if [[ -z "$changes" ]]; then
            echo "Nothing to commit"
          else
            echo "Committing change"
            echo "$changes"
            git commit -m "Update versions"
            git push
          fi
